version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:14.15.1

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build
          command: yarn run build

workflows:
  version: 2
  build:
    jobs:
      - build
